# Generated by Django 5.2.1 on 2025-05-30 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='duration',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Срок обучения (лет)'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='level',
            field=models.CharField(choices=[('bachelor', 'Бакалавриат'), ('master', 'Магистратура'), ('specialist', 'Специалитет'), ('phd', 'Аспирантура')], default='bachelor', max_length=20, verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='tuition_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость обучения (в год)'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='budget_places',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество бюджетных мест'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='code',
            field=models.CharField(help_text='Код по ФГОС, например: 09.03.01', max_length=20, verbose_name='Код программы'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='description',
            field=models.TextField(help_text='Подробное описание программы обучения', verbose_name='Описание программы'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='name',
            field=models.CharField(help_text="Полное название программы, например: 'Компьютерные науки'", max_length=255, verbose_name='Название программы'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='paid_places',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество платных мест'),
        ),
    ]
